version: '3'
services:
  axonserver:
    image: axoniq/axonserver:4.1.2-jdk11
    hostname: axonserver
    environment:
      - AXONSERVER_HOSTNAME=axonserver
    volumes:
      - axonserver-data:/opt/axonserver/data
  gateway:
    build: gateway
    image: consdata/heimdall-gateway:${HEIMDALL_VERSION:-latest}
    ports:
      - "8200:80"
    depends_on:
      - backend
  frontend:
    build: frontend
    image: consdata/heimdall-frontend:${HEIMDALL_VERSION:-latest}
  backend:
    build: backend
    image: consdata/heimdall-backend:${HEIMDALL_VERSION:-latest}
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver
      - APP_INSTANCE_UUID=7a784ff31438
      - JAVA_XMX=512m
    depends_on:
      - axonserver
volumes:
  axonserver-data:
