apiVersion: v1
kind: Service
metadata:
  name: heimdall-monitor-tracking
  labels:
    app: heimdall-monitor-tracking
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: heimdall-monitor-tracking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-monitor-tracking
  labels:
    app: heimdall-monitor-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall-monitor-tracking
  template:
    metadata:
      labels:
        app: heimdall-monitor-tracking
    spec:
      containers:
        - name: heimdall-monitor-tracking
          image: consdata/heimdall-monitor-tracking:0.1.7
          env:
            - name: APP_INSTANCE_UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AXON_AXONSERVER_SERVERS
              value: heimdall-axonserver
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
